### ISSUE TITLE
Incompatibility bug with Compatibility Checker (ironically)

### ISSUE THREAD

**Issue by NilaierMusic** [echoman-dev/LCLobbyListFix#2]
Seems like there's an incompatibility error with the mod [CompatibilityChecker](https://github.com/VisualError/CompatibilityChecker/) by [VisualError](https://github.com/VisualError) that causes this bug to happen:
![Lethal_Company_fiHdaK0hBx](https://github.com/echoman-dev/LCLobbyListFix/assets/86863646/b4b7059a-3586-4ec9-8378-3f9380265c56)

**Comment by echoman-dev** [comment]
Thank you for opening this ticket! Probably first of many of this kind.

[Visual Error](https://github.com/VisualError) fixed the scrollbar issue in both [CompatibilityChecker](https://github.com/VisualError/CompatibilityChecker/) & [Better Lobbies](https://github.com/VisualError/Better-Lobbies) by recalculating the size of the scrollable area. The solution I opted for (adding a couple of components to make Unity do these calculations) seems to lead to the above result with either mod, so I've added an incompatibility check to skip mine if either of the above is installed.
